"""card model updated

Revision ID: 5aae0788505f
Revises: 6359803582bb
Create Date: 2026-02-28 01:10:59.534069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '5aae0788505f'
down_revision: Union[str, Sequence[str], None] = '6359803582bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    card_status_enum = postgresql.ENUM(
        'active',
        'inactive',
        'blocked',
        name='cardstatus'
    )

    card_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'cards',
        sa.Column('status', card_status_enum, nullable=False)
    )
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('cards', sa.Column('issue_data', sa.DateTime(), nullable=False))
    op.add_column('cards', sa.Column('expiry_data', sa.DateTime(), nullable=False))
    op.add_column('machines', sa.Column('status', sa.Enum('online', 'offline', 'busy', 'a', name='machinestatus'), nullable=False))
    op.drop_constraint(op.f('punch_history_arcade_id_fkey'), 'punch_history', type_='foreignkey')
    op.create_foreign_key(None, 'punch_history', 'arcades', ['arcade_id'], ['id'])
    op.add_column('recharge_history', sa.Column('payment_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('cards', 'status')

    card_status_enum = postgresql.ENUM(
        'active',
        'inactive',
        'blocked',
        name='cardstatus'
    )

    card_status_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_column('recharge_history', 'payment_type')
    op.drop_constraint(None, 'punch_history', type_='foreignkey')
    op.create_foreign_key(op.f('punch_history_arcade_id_fkey'), 'punch_history', 'arcades', ['arcade_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('machines', 'status')
    op.drop_column('cards', 'expiry_data')
    op.drop_column('cards', 'issue_data')
    op.drop_column('cards', 'status')
    # ### end Alembic commands ###
