"""added arcade_id to punchhist

Revision ID: 6359803582bb
Revises: fa7d6e8bc10e
Create Date: 2026-02-27 23:59:42.946942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6359803582bb'
down_revision: Union[str, Sequence[str], None] = 'fa7d6e8bc10e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('punch_history', sa.Column('arcade_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'punch_history', 'arcades', ['arcade_id'], ['id'])
    op.add_column('recharge_history', sa.Column('payment_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recharge_history', 'payment_type')
    op.drop_constraint(None, 'punch_history', type_='foreignkey')
    op.drop_column('punch_history', 'arcade_id')
    # ### end Alembic commands ###
