"""intial commit

Revision ID: b3c99c20cc86
Revises: 
Create Date: 2026-02-25 12:55:54.352234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c99c20cc86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arcades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arcades_id'), 'arcades', ['id'], unique=False)
    op.create_table('cards',
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('contact_no', sa.String(length=10), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('arcade_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['arcade_id'], ['arcades.id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_index(op.f('ix_cards_card_id'), 'cards', ['card_id'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cost_per_play', sa.Float(), nullable=True),
    sa.Column('arcade_id', sa.String(), nullable=True),
    sa.Column('secret_key', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('online', 'offline', 'busy', 'a', name='machinestatus'), nullable=False),
    sa.ForeignKeyConstraint(['arcade_id'], ['arcades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('arcade_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['arcade_id'], ['arcades.id'], ),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('punch_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=True),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('cost_at_time', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.card_id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_punch_history_id'), 'punch_history', ['id'], unique=False)
    op.create_table('recharge_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.card_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recharge_history_id'), 'recharge_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recharge_history_id'), table_name='recharge_history')
    op.drop_table('recharge_history')
    op.drop_index(op.f('ix_punch_history_id'), table_name='punch_history')
    op.drop_table('punch_history')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_cards_card_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_arcades_id'), table_name='arcades')
    op.drop_table('arcades')
    # ### end Alembic commands ###
